Canillitapp/headlines-iOS

- Headlines/src/Controllers/RecentNewsViewController.swift
- Headlines/src/Controllers/TrendingCardsViewController.swift
> Added pull to refresh on both lists

- Headlines/src/Controllers/TrendingCardsViewController.swift
> fix: avoid showing news without an image

- Headlines.xcodeproj/project.pbxproj
- Headlines/AppDelegate.swift
- Podfile
- Podfile.lock
... and hiding tokens at the same time :-)
https://www.herzbube.ch/blog/2016/08/how-hide-fabric-api-key-and-build-secret-open-source-project
> Added support on Crashlytics

- Headlines.xcodeproj/project.pbxproj
- Headlines/Base.lproj/Main.storyboard
- Headlines/Info.plist
- Headlines/src/Controllers/OrientationAwareControllers.swift
- Headlines/src/Controllers/TrendingCardsViewController.swift
- Headlines/src/config.plist
- HeadlinesTests/Info.plist
- HeadlinesUITests/Info.plist
- Watch Extension/Info.plist
- Watch/Info.plist
- fastlane/README.md
> iPad support

- Headlines/src/Controllers/NewsTableViewController.swift
- Headlines/src/Services/ReactionsService.swift
- Watch Extension/Reaction.swift
> Feat unreact

- Headlines.xcodeproj/project.pbxproj
- Headlines/Base.lproj/Main.storyboard
- Headlines/src/Controllers/TrendingCardsViewController.swift
- Watch Extension/NewsService.swift
fix: loading indicator when there's data fetching on bottom #17
> fix: loading indicator when there's data fetching on bottom

- Headlines/src/Controllers/MyReactionsViewController.swift
- Headlines/src/Controllers/NewsTableViewController.swift
- Headlines/src/Controllers/PopularNewsViewController.swift
- Headlines/src/Controllers/RecentNewsViewController.swift
- Headlines/src/Controllers/SearchViewController.swift
- Headlines/src/Services/ReactionsService.swift
> Fix errors

- Headlines/src/Controllers/NewsTableViewController.swift
> feat: analytics, posted_reaction

- Headlines/src/Controllers/NewsTableViewController.swift
- Headlines/src/Controllers/PopularNewsViewController.swift
- Headlines/src/ViewModels/NewsCellViewModel.swift
> Fix dates on popular

- Watch/Base.lproj/Interface.storyboard
> fix: removed separator on Apple Watch app

- .travis.yml
- Common/services/NewsService.swift
- Common/services/mocks/GET-trending.json
- Headlines.xcodeproj/project.pbxproj
- Headlines.xcodeproj/xcshareddata/xcschemes/HeadlinesUITests.xcscheme
- Headlines.xcodeproj/xcuserdata/betzerra.xcuserdatad/xcschemes/xcschememanagement.plist
- HeadlinesTests/HeadlinesTests.swift
- HeadlinesUITests/HeadlinesUIMockedTests.swift
- HeadlinesUITests/HeadlinesUITests.swift
- SnapshotUITests/SnapshotUITests.swift
- fastlane/Fastfile
- Working on tests to improve snapshot automation
> Fix mocked json

- Headlines/Base.lproj/LaunchScreen.storyboard
- Headlines/Base.lproj/Main.storyboard
- Headlines/src/Controllers/LoadingViewController.swift
> fix: launch screen background

- Headlines/src/Controllers/InitialTabBarController.swift
- Headlines/src/Controllers/OrientationAwareControllers.swift
- Headlines/src/ScreenSwitcher/ScreenSwitcherViewController.swift
> fix: iPhones do not have landscape mode

- Canillitapp Widget/Info.plist
- Common/services/mocks/GET-trending.json
- Headlines.xcodeproj/project.pbxproj
- Headlines/Info.plist
- Headlines/src/ViewModels/ReviewBannerViewModel.swift
- HeadlinesMockedUITests/HeadlinesMockedUITests.swift
- HeadlinesMockedUITests/Info.plist
- HeadlinesTests/Info.plist
- HeadlinesUITests/Info.plist
- SnapshotUITests/Info.plist
- SnapshotUITests/SnapshotUIReviewBannerTests.swift
- SnapshotUITests/SnapshotUITests.swift
- Watch Extension/Info.plist
- Watch/Info.plist
> feat: added snapshots to review banner feature

- Canillitapp Widget/Info.plist
- Common/models/News.swift
- Headlines.xcodeproj/project.pbxproj
- Headlines/Info.plist
- Headlines/src/Controllers/NewsTableViewController.swift
- Headlines/src/ViewModels/NewsCellViewModel.swift
- HeadlinesMockedUITests/Info.plist
- HeadlinesTests/Info.plist
- HeadlinesUITests/Info.plist
- SnapshotUITests/Info.plist
- Watch Extension/Info.plist
- Watch/Info.plist
> Display category on cell (if any)

- Headlines.xcodeproj/project.pbxproj
- Headlines/src/Controllers/InitialTabBarController.swift
- Headlines/src/Controllers/MyReactionsViewController.swift
- Headlines/src/Controllers/NewsTableViewController.swift
- Headlines/src/Controllers/TrendingCardsViewController.swift
- Headlines/src/Protocols/TabbedViewController.swift
> feat: double tap scrolls to top

- Common/models/News.swift
- Headlines.xcodeproj/project.pbxproj
- Headlines/src/Controllers/InitialTabBarController.swift
- Headlines/src/Controllers/NewsTableViewController.swift
- Headlines/src/Controllers/ProfileViewController.swift
- Headlines/src/Controllers/SearchViewController.swift
- Headlines/src/Controllers/TrendingCardsViewController.swift
- Headlines/src/Services/ContentViewsService.swift
- Headlines/src/config.plist
> Feat analytics

- Common/services/HTTPService.swift
- Common/services/NewsService.swift
> feat: track search

- Canillitapp Widget/Info.plist
- Headlines.xcodeproj/project.pbxproj
- Headlines/Base.lproj/Trending.storyboard
- Headlines/Info.plist
- HeadlinesMockedUITests/Info.plist
- HeadlinesTests/Info.plist
- HeadlinesUITests/Info.plist
- Notifications/Info.plist
- SnapshotUITests/Info.plist
- Watch Extension/Info.plist
- Watch/Info.plist
> Feat eye candy

- Common/services/mocks/GET-popular.json
- Common/services/mocks/GET-recent.json
This will lead to better screenshots.
> chore: updated mock data (added category attribute on news)

- Headlines/src/Controllers/NewsTableViewController.swift
> fix: #102 Peek and Pop at Buscar

- Dangerfile
> chore: thank other people

- Headlines/Base.lproj/NewsPreview.storyboard
> feat: improvement on UI at Peek and pop

- Headlines/src/Controllers/Search/NewsSearchViewController.swift
> fix: date format on search #114

- Canillitapp Widget/Info.plist
- Common/services/NewsService.swift
- Headlines.xcodeproj/project.pbxproj
- Headlines.xcodeproj/xcuserdata/betzerra.xcuserdatad/xcschemes/Headlines.xcscheme
- Headlines/Info.plist
- Headlines/resources/GET-search-term.json
- Headlines/resources/GET-search-trending.json
- Headlines/src/Controllers/Search/TrendingSearchViewController.swift
- HeadlinesMockedUITests/Info.plist
- HeadlinesTests/Info.plist
- HeadlinesUITests/Info.plist
- Notifications/Info.plist
- SnapshotUITests/Info.plist
- SnapshotUITests/SnapshotUITests.swift
- Watch Extension/Info.plist
- Watch/Info.plist
> Fix ui tests

- Headlines/Base.lproj/Filter.storyboard
- Headlines/src/Controllers/FilterViewController.swift
- Headlines/src/DataSources/FilterCategoriesDataSource.swift
- Headlines/src/DataSources/FilterSourcesDataSource.swift
> fix: self sizing cell issue on iOS 12

- Canillitapp Widget/Info.plist
- Headlines.xcodeproj/project.pbxproj
- Headlines/AppDelegate.swift
- Headlines/Info.plist
- Headlines/src/Controllers/DismissableNavigationController.swift
- Headlines/src/Controllers/ProfileViewController.swift
- Headlines/src/Controllers/Search/SearchViewController.swift
- Headlines/src/Controllers/Search/TrendingSearchViewController.swift
- Headlines/src/Controllers/TrendingCardsViewController.swift
- Headlines/src/Helpers/SuggestionsHelper.swift
- Notifications/Info.plist
- Watch Extension/Info.plist
- Watch/Info.plist
> Siri suggestions for search

- Headlines/Base.lproj/Trending.storyboard
- Headlines/NewsTableViewCell.xib
> fix: constraints warnings on UITableViewCell

- Common/services/mocks/GET-trending.json
- Headlines/src/Controllers/TrendingNewsTableViewController.swift
- HeadlinesMockedUITests/HeadlinesMockedUITests.swift
- SnapshotUITests/SnapshotUITests.swift
- fastlane/Snapfile
> chore: automated screenshots for Trending screen detail #150

- Common/services/NewsService.swift
- changelog.md
> Fix: search tracking

- Headlines/src/Controllers/NewsTableViewController.swift
- Headlines/src/Controllers/TrendingNewsTableViewController.swift
- changelog.md
> fix: force touch (peak and pop) at TrendingNews screen

- Headlines/Settings.bundle/Root.plist
- Headlines/src/Controllers/NewsTableViewController.swift
- Headlines/src/Controllers/ProfileViewController.swift
- Headlines/src/Controllers/TrendingNewsTableViewController.swift
- Headlines/src/Managers/UserSettingsManager.swift
- changelog.md
> Fix: handling open news

- Canillitapp Widget/TodayViewModel.swift
- Headlines.xcodeproj/project.pbxproj
- Headlines.xcodeproj/xcshareddata/xcschemes/Headlines.xcscheme
- Headlines.xcodeproj/xcshareddata/xcschemes/HeadlinesMockedUITests.xcscheme
- Headlines.xcodeproj/xcshareddata/xcschemes/HeadlinesTests.xcscheme
- Headlines.xcodeproj/xcshareddata/xcschemes/HeadlinesUITests.xcscheme
- Headlines.xcodeproj/xcshareddata/xcschemes/SnapshotUITests.xcscheme
- Headlines/AppDelegate.swift
- Headlines/src/Activities/ShareCanillitapActivity.swift
- Headlines/src/Controllers/DismissableNavigationController.swift
- Headlines/src/Controllers/InitialTabBarController.swift
- Headlines/src/Controllers/LoadingViewController.swift
- Headlines/src/Controllers/NewsTableViewController+Reaction.swift
- Headlines/src/Controllers/NewsTableViewController.swift
- Headlines/src/Controllers/SettingsViewController.swift
- Headlines/src/Controllers/State/SpinnerViewController.swift
- Headlines/src/DataSources/FilterSourcesDataSource.swift
- Headlines/src/Extensions/UIKit/UIViewController+Child.swift
- Headlines/src/ScreenSwitcher/ScreenSwitcherViewController.swift
- Headlines/src/ViewModels/NewsCellViewModel.swift
- Headlines/src/Views/SuggestedTermTableViewCell.swift
> chore: updated to Swift 5

- Canillitapp Widget/Info.plist
- Headlines.xcodeproj/project.pbxproj
- Headlines/Info.plist
- HeadlinesMockedUITests/Info.plist
- HeadlinesTests/Info.plist
- HeadlinesUITests/Info.plist
- Notifications/Info.plist
- Notifications/Notifications.entitlements
- SnapshotUITests/Info.plist
- Watch Extension/Info.plist
- Watch/Info.plist
> Feat implement catalyst

- Canillitapp Widget/Info.plist
- Headlines.xcodeproj/project.pbxproj
- Headlines/Info.plist
- HeadlinesMockedUITests/Info.plist
- HeadlinesTests/Info.plist
- HeadlinesUITests/Info.plist
- Notifications/Info.plist
- SnapshotUITests/Info.plist
- Watch Extension/Info.plist
- Watch/Info.plist
> chore: version bump
